{
 "title": "Latency",
 "description": "Host latency summary",
 "tags": [
  "ping",
  "latency"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Mean over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Latencia" }
   ],
   "targets": [
    { "expr": "rustyping_ping_last", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(rustyping_ping_last)" }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "bottomk(1, rustyping_ping_last)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "errors/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(rustyping_ping_error[10s])) / 10"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "topk(1, rustyping_ping_last)", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Global Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rustyping_host_up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le) (rustyping_ping_latency_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Health over time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rustyping_host_up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Lost",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rustyping_host_up == 0", "legendFormat": "{{name}}" }
   ]
  }
 ]
}